from pathlib import Path
import html, zipfile, hashlib, math
ROOT=Path(__file__).resolve().parent
PUBLIC=ROOT/'public'
# Remove the retired generated page on rebuild; its source remains below.
(PUBLIC/'resources.html').unlink(missing_ok=True)
NAV=[('index','Home'),('simulator','Simulator'),('development','Development'),('about','About'),('contact','Contact')]
# Three narrow Gaussian peaks, sampled finely enough to remain smooth at any size.
def gaussian_logo_path():
    points = []
    for i in range(153):
        x = 3 + i / 4
        y = 35 - 12 * math.exp(-0.5 * ((x - 11) / 0.9) ** 2) - 21 * math.exp(-0.5 * ((x - 22) / 0.95) ** 2) - 29 * math.exp(-0.5 * ((x - 33) / 1.05) ** 2)
        points.append(f'{"M" if i == 0 else "L"}{x:.2f} {y:.3f}')
    return ' '.join(points)

peak_path = gaussian_logo_path()
logo=f'<svg viewBox="0 0 44 44" aria-hidden="true"><path d="{peak_path}" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round" stroke-linecap="round"/><path d="M3 40h38" stroke="currentColor" opacity=".4"/></svg>'
(PUBLIC/'assets/favicon.svg').write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 44 44"><rect width="44" height="44" rx="8" fill="#3b1900"/><path d="{peak_path}" fill="none" stroke="white" stroke-width="1.8" stroke-linejoin="round" stroke-linecap="round"/></svg>')

def page(slug,title,desc,body,extra=''):
    nav=''.join(f'<a href="/{"" if k=="index" else k+".html"}" '+('aria-current="page"' if k==slug else '')+f'>{v}</a>' for k,v in NAV)
    text=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} — GC Simulator</title><meta name="description" content="{html.escape(desc,quote=True)}"><meta name="theme-color" content="#3b1900"><link rel="canonical" href="https://gcsimulator.org/{'' if slug=='index' else slug}"><link rel="stylesheet" href="/assets/site.css"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">{extra}<script src="/assets/site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="header"><div class="wrap masthead"><a class="brand" href="/">{logo}<span><strong>GC Simulator</strong><small>the free, open-source GC simulator</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="site-nav">Menu</button></div><div class="nav-band"><nav id="site-nav" class="wrap nav" aria-label="Main navigation">{nav}</nav></div></header><main id="main" class="wrap">{body}</main><footer class="footer"><div class="wrap"><div class="footer-top"><div><a class="footer-brand" href="/">GC Simulator</a></div><div class="footer-links"><a href="/about.html">About the project</a><a href="/development.html">Source code</a><a href="https://hplcsimulator.org">HPLC Simulator ↗</a></div></div><div class="footer-bottom"><span>GC Simulator by Paul Boswell</span><a href="https://creativecommons.org/licenses/by-nc-sa/3.0/us/">CC BY-NC-SA 3.0 US</a></div></div></footer></body></html>'''
    import re
    def version_asset(m):
        path=m[1];file=PUBLIC/path.lstrip('/')
        return '"'+path+'?v='+hashlib.sha256(file.read_bytes()).hexdigest()[:10]+'"' if file.exists() else m[0]
    text=re.sub(r'"(/assets/[^"?]+\.(?:css|js|svg))"',version_asset,text)
    (PUBLIC/f'{slug}.html').write_text(text,encoding='utf-8')
def heading(k,title,p):return f'<div class="page-heading"><h1>{title}</h1><p>{p}</p></div>'
def panel(title,p):return '<article class="panel">'+(f'<h2>{title}</h2>' if title else '')+p+'</article>'

page('index','Explore gas chromatography','A free interactive gas chromatography simulator. Explore temperature programs, carrier gases, column dimensions, and sample separations.', '''<section class="hero"><div><h1>Gas chromatography<br><em>simulator</em></h1><p class="intro">Simulate gas chromatography with isothermal and temperature-programmed methods. Adjust a variety of parameters including temperature, carrier gas, flow, column dimensions, and sample composition to compare separations.</p><div class="actions"><a class="button" href="/simulator.html">Launch GC Simulator <span class="arrow">↗</span></a></div><p class="quiet-note">No installation, account, or Java plug-in required.</p></div><figure class="hero-figure simulator-preview"><a class="preview-image-link" href="/simulator.html"><img src="/assets/simulator-preview.svg" alt="Simulated GC chromatogram from the original 15-compound sample"></a></figure></section>''')

lessons=[('temperature','Temperature & retention','Start at 200 °C. Save a reference, then lower the oven to 150 °C and raise it to 250 °C.','Which compounds move most? How do analysis time and peak spacing change? Why might a faster run make a pair harder to separate?'),('program','A programmed separation','Switch to temperature programming: 60 °C for 1 min, then 20 °C/min to 260 °C. Compare with the isothermal method.','Which early peaks benefit from the cool start? Change the ramp to 10 and 40 °C/min. Compare retention, widths, and resolution.'),('carrier','Carrier gas & flow','Keep the column and oven fixed. Compare helium, hydrogen, and nitrogen, then vary the flow from 0.5 to 3 mL/min.','How do required inlet pressure, plate count, and analysis time change? Does the fastest flow give the narrowest relative peaks?'),('column','Column dimensions','Compare a 15 m, 30 m, and 60 m column at the same flow and temperature. Then double the film thickness.','What happens to retention, pressure, and resolution? Explain why changing film thickness can change retention even at the same flow.'),('injection','Injection & detector response','Compare a 100:1 split with a 10:1 split, then splitless injection. Keep concentration and injection volume fixed.','Compare the amount on column and peak width. Increase the detector time constant: what happens to noise and closely spaced peaks?')]
cards=''.join(f'<article class="resource-card"><span class="tag">Experiment {i+1:02d} · GC fundamentals</span><h2>{t}</h2><p>{p}</p><p><strong>Investigate:</strong> {q}</p><a class="text-link" href="/simulator.html?lesson={key}">Open this experiment <span>→</span></a></article>' for i,(key,t,p,q) in enumerate(lessons))
# Retained for possible restoration; excluded from navigation and the published site.
if False: page('resources','Educational resources','Guided GC experiments for students and instructors.',heading('Learn by doing','Educational resources','Five guided experiments connect GC method settings to retention, efficiency, and resolution. Use them independently or as prompts for classroom discussion.')+f'<div class="resource-grid">{cards}</div><section class="section"><h2>Make a useful comparison</h2><div class="steps"><div class="step"><span class="step-number">01</span><h3>Keep a reference</h3><p>Use “Keep reference” before you change a setting. The original trace stays visible for comparison.</p></div><div class="step"><span class="step-number">02</span><h3>Change one variable</h3><p>Record retention time, peak width, and resolution. Compare the numerical results as well as the graph.</p></div><div class="step"><span class="step-number">03</span><h3>Save your evidence</h3><p>Download your method, CSV, or plot image. Share the method file to reproduce the same experiment.</p></div></div></section>')
page('about','About','About GC Simulator, its creator, educational purpose, and original funding.',heading('About this project','About GC Simulator','GC Simulator is a free resource for anyone interested in understanding gas chromatography.')+ '<section class="about-overview" aria-labelledby="contributors-title"><h2 id="contributors-title">Contributors</h2><div class="people"><div class="person"><h3>Paul Boswell</h3><p>GC Simulator</p><p>Originally at the University of Minnesota; now at Upper Story LLC.</p></div></div></section><section class="content-bottom"><h2>Project support</h2><div class="funding-grid"><article class="funding-card"><a class="funding-logo" href="https://www.upperstory.com/"><img src="/assets/upper-story.svg" alt="Upper Story" width="190" height="83" loading="lazy"></a><h3>Upper Story LLC</h3><p>Project support</p></article><div class="funding-card"><a class="funding-logo" href="https://www.nih.gov"><img src="/assets/nih.jpg" alt="National Institutes of Health"></a><h3>National Institutes of Health</h3><p>The original GC Simulator acknowledged support through grant R01GM098290.</p></div></div></section>')
page('development','Development','GC Simulator source downloads and numerical model documentation.',heading('Open source','Development','Download the simulator source code and read the numerical model documentation.')+'<div class="about-overview">'+panel('Source & documentation','<ul class="download-list"><li><a href="https://github.com/pgboswell/gc-simulator">GC Simulator repository <small>GitHub ↗</small></a></li><li><a href="https://github.com/pgboswell/gc-simulator-website">GC Simulator website repository <small>GitHub ↗</small></a></li><li><a href="/downloads/gc-simulator-java-source.zip" download>Original Java source <small>ZIP</small></a></li><li><a href="/MODEL.md">Model and verification notes <small>Markdown</small></a></li></ul><p>Distributed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 US license.</p><p><a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/3.0/us/"><img src="/assets/cc-by-nc-sa.png" width="88" height="31" alt="Creative Commons Attribution-Noncommercial-Share Alike 3.0 US license"></a></p>')+'</div>')
page('contact','Contact','Contact the GC Simulator project.',heading('Get in touch','Contact','Send a question, bug report, or message about teaching materials.')+'''<div class="split"><section class="panel"><h2>Send a message</h2><form id="contact-form" action="/api/contact" method="post"><label for="name">Your name</label><input id="name" name="name" required maxlength="120" autocomplete="name"><label for="email">Email address</label><input id="email" name="email" type="email" required maxlength="254" autocomplete="email"><label for="subject">Subject</label><input id="subject" name="subject" required maxlength="160"><label for="message">Message</label><textarea id="message" name="message" rows="7" required maxlength="10000"></textarea><div class="contact-trap" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><div id="contact-challenge"></div><button class="button" type="submit" disabled>Send message</button><p id="contact-status" role="status">Checking messaging availability…</p><noscript><p>Enable JavaScript to use this contact form.</p></noscript></form></section><aside class="panel"><h2>Reporting a simulation issue?</h2><p>Include the settings you changed, the compound names, and what you expected to see. Saving the method in the simulator is a useful way to keep a reproducible example.</p></aside></div>''', '<script src="/assets/contact.js" defer></script>')
page('simulator','Interactive gas chromatography simulator','Interactive gas chromatography simulator with 102 compounds and temperature programming.',(ROOT/'simulator/workspace.html').read_text(encoding='utf-8'),'<link rel="stylesheet" href="/assets/simulator/simulator.css"><script type="module" src="/assets/simulator/app.js"></script>')
(PUBLIC/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>https://gcsimulator.org/{"" if k=="index" else k}</loc></url>' for k,_ in NAV)+'</urlset>')
(PUBLIC/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: https://gcsimulator.org/sitemap.xml\n')
(PUBLIC/'downloads').mkdir(exist_ok=True)
with zipfile.ZipFile(PUBLIC/'downloads/gc-simulator-java-source.zip','w',zipfile.ZIP_DEFLATED) as z:
    src=ROOT/'legacy-source/src'
    for p in src.rglob('*'):
        if p.is_file():z.write(p,str(Path('src')/p.relative_to(src)))
with zipfile.ZipFile(PUBLIC/'downloads/gc-simulator-web.zip','w',zipfile.ZIP_DEFLATED) as z:
    for folder in ['public','simulator','scripts','tests','functions','legacy-source']:
        for p in (ROOT/folder).rglob('*'):
            if p.is_file() and p.suffix not in ['.zip','.class'] and 'java' not in p.relative_to(ROOT).parts:z.write(p,str(p.relative_to(ROOT)))
    for name in ['build_site.py','package.json','worker.js','wrangler.jsonc','README.md','HPLC-PARITY.md']:
        if (ROOT/name).exists():z.write(ROOT/name,name)
print('Built GC website pages and source downloads.')
